replicacount: 1

discoveryEngineImage:
   repository: accuknox/knoxautopolicy:stable
   pullPolicy: Always 

#lables
labels:
  app: discovery-engine

#deployment name
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#Environment variables
env:
  tenant_id: "0"
  cluster_id: "0"
  cluster_name: "default"
  workspace_id: "0"

#ServiceAccount
serviceAccount: 
  create: true
  name: discovery-engine
  Namespace: 
  
service:
  enabled: true
  name: discovery-engine
  type: ClusterIP
  protocol: TCP
  port: 9089
  targetPort: 9089

#role
clusterRole:
  create: true
  name: discovery-engine-role
  rules:
  - apiGroups: ["*"]
    resources: ["pods", "services", "deployments", "endpoints", "namespaces", "nodes", "replicasets", "statefulsets", "daemonsets", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  
#clusterroleBinding
clusterRoleBinding:
  create: true
  name: discovery-engine-role-binding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: discovery-engine-role
  subjects:
  - kind: ServiceAccount
    name: discovery-engine
    
containerPortDiscoveryEngine:
  - containerPort: 9089

#Configmap DiscoveryEngine
configmapDiscoveryEngine:
  name: discovery-engine-config
  enabled: true
  app: configmapfiles/discovery-engine/conf.yaml

#volumes DiscoveryEngine
volumesDiscoveryEngine:
- name: discovery-engine-config-volume
  configMap:
    name: discovery-engine-config

#volumeMounts DiscoveryEngine
volumeMountsDiscoveryEngine:
- name: discovery-engine-config-volume
  mountPath: /conf
  readOnly: true

#resource DiscoveryEngine
resourcesDiscoveryEngine:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
