# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/mimetic-kit-294408/production/knoxautopolicy
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

labels:
  app: knoxautopolicy
  env: prod

namespace: accuknox-knoxautopolicy

#serviceaccountnamespace
namespace:
  name: explorer

volumeMounts:
  - mountPath: /conf
    name: config-volume
    readOnly: true
  - mountPath: /kafka-ssl
    name: knoxautopolicy-kafka-ssl-volume
    readOnly: true
volumes:
  - name: config-volume
    configMap:
      name: knoxautopolicy-config
  - name: knoxautopolicy-kafka-ssl-volume
    secret:
      secretName: knoxautopolicy-kafka-ssl

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9089

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 800m
    memory: 2Gi
  limits:
    cpu: 800m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

nodeSelector: {}

tolerations: []

affinity: {}

# conf.yaml
config:
  application:
    name: knoxautopolicy
    network:
      operation-mode: 1                         # 1: cronjob | 2: one-time-job
      cron-job-time-interval: "0h0m30s"         # format: XhYmZs 
      operation-trigger: 10000
      network-log-limit: 10000
      network-log-from: "kafka"                    # db|hubble
      network-log-file: "./flow.json"           # file path
      network-policy-to: "db"              # db, file
      network-policy-dir: "./"
      network-policy-types: 3
      network-policy-rule-types: 511
      skip-cert-verification: true
    system:
      operation-mode: 1                         # 1: cronjob | 2: one-time-job
      cron-job-time-interval: "0h0m30s"         # format: XhYmZs
      operation-trigger: 1000
      system-log-limit: 10000 
      system-log-from: "kafka"                     # db|kubearmor
      system-log-file: "./log.json"             # file path
      system-policy-to: "db"               # db, file
      system-policy-dir: "./"
      deprecate-old-mode: true
    cluster:
      cluster-info-from: "accuknox"            # k8sclient|accuknox
      cluster-mgmt-url: "https://api.accuknox.com"

  database:
    driver: mysql
    host: accuknox-mysql-haproxy.accuknox-mysql.svc.cluster.local
    port: 3306
    user: accuknox_user
    password: EAy5Kq4uhc5Gkws
    dbname: accuknox
    table-network-log: network_log
    table-network-policy: network_policy
    table-system-log: system_log
    table-system-alert: system_alert
    table-system-policy: system_policy

  feed-consumer:
    kafka:
      number-of-consumers: 3
      broker-address-family: v4
      session-timeout-ms: 6000
      auto-offset-reset: "latest" # earliest | latest
      bootstrap-servers: "accuknox-kafka-bootstrap.accuknox-kafka.svc.cluster.local:9092"
      group-id: knoxautopolicy
      topics: 
        - cilium-alerts
        - kubearmor-alerts
      security:
        protocol: SSL
      ssl:
        enabled: false
      ca:
        location: /kafka-ssl/ca.pem
      keystore:
        location: /kafka-ssl/user.p12
        pword: DHmHwNYy22At
      events:
        buffer: 50

  logging:
    level: "INFO"
    
  cilium-hubble:
    url: 10.4.41.240
    port: 80
